feat: add some config flags with bitflags in chapter 11
rustsbi/rustsbi pull request #74
Opened 2024-08-12 15:19 UTC by GrassedgeT

Add  some config flags with bitflags crate in chapter 11

These flags declared in: 

Table 36(PMU Counter Config Match Flags),
Table 38(PMU Counter Start Flags),
Table 40(PMU Counter Stop Flags).

2024-10-21 04:14 UTC, luojia65 commented
Thanks for your contribution! I'll look into it, but I may have better options for the module name `counter_related`. What about the name `flags`?

2024-10-21 04:16 UTC, luojia65 requested changes

2024-10-21 04:16 UTC, luojia65 commented on sbi-spec/src/pmu.rs
> +/// Declared in §11.7 §11.8 §11.9.
```suggestion
/// Declared in §11.7, §11.8 and §11.9.
```

2024-10-21 04:16 UTC, luojia65 commented on sbi-spec/src/pmu.rs
> +        pub struct CounterCfgFlags: usize{
```suggestion
        pub struct CounterCfgFlags: usize {
```

2024-10-21 04:16 UTC, luojia65 commented on sbi-spec/src/pmu.rs
> +        pub struct CounterStopFlags: usize{
```suggestion
        pub struct CounterStopFlags: usize {
```

2024-10-21 04:16 UTC, luojia65 commented on sbi-spec/src/pmu.rs
> +        pub struct CounterStartFlags: usize{
```suggestion
        pub struct CounterStartFlags: usize {
```

2024-10-25 07:47 UTC, GrassedgeT commented
Thanks for your contribution! I'll look into it, but I may have better options for the module name `counter_related`. What about the name `flags`?
Translated Text: >
BTW, please add a changelog entry for your contribution.

Ok, I have limited experience in contributing, thanks for the advice.

2024-10-25 08:55 UTC, luojia65 commented
I'll review recently, thanks!

2024-10-26 06:26 UTC, luojia65 approved these changes
LGTM, I'll adjust documents and modify those structure names later.

2024-10-26 06:26 UTC, merged